DROP TABLE IF EXISTS `metadata_driver_hist`;
CREATE TABLE `metadata_driver_hist` (
	`id` bigint(11) DEFAULT NULL COMMENT 'id',
	`masterId` bigint(11) DEFAULT NULL COMMENT 'masterId',
	`licenseNumber` varchar(100) DEFAULT NULL COMMENT '驾驶证编号',
	`driverName` varchar(255) DEFAULT NULL COMMENT '驾驶员姓名',
	`driverPhone` varchar(100) DEFAULT NULL COMMENT '驾驶员电话',
	`driverIdCard` varchar(100) DEFAULT NULL COMMENT '驾驶员身份证',
	`driverAddress` varchar(255) DEFAULT NULL COMMENT '驾驶员地址',
	`licenseImage` varchar(255) DEFAULT NULL COMMENT '驾驶证图片',
	`hvps` varchar(255) DEFAULT NULL COMMENT '回乡证',
	`hvpsImage` varchar(255) DEFAULT NULL COMMENT '回乡证照片',
	`passport` varchar(255) DEFAULT NULL COMMENT '护照',
	`passportImage` varchar(255) DEFAULT NULL COMMENT '护照照片',
	`inchImage` varchar(255) DEFAULT NULL COMMENT '一寸照片',
	`birthday` varchar(255) DEFAULT NULL COMMENT '生日',
	`sex` int(2) DEFAULT NULL COMMENT '性别',
	`quasi` varchar(255) DEFAULT NULL COMMENT '准驾车型',
	`idcardFace` varchar(255) DEFAULT NULL COMMENT '身份证正面',
	`idcardBack` varchar(255) DEFAULT NULL COMMENT '身份证反面',
	`licenseValidTime` varchar(255) DEFAULT NULL COMMENT '驾驶证有效期',
	`driverId` bigint(11) DEFAULT NULL COMMENT 'driverId',
	`licenseStartTime` varchar(50) DEFAULT NULL COMMENT '駕駛證初次領證日期',
	`seconddrivername` varchar(50) DEFAULT NULL COMMENT '第二姓名',
	`idcardValidTime` varchar(50) DEFAULT NULL COMMENT '身份证有效期',
	`certificateType` tinyint(4) DEFAULT NULL COMMENT '证件类型（1护照  2：回乡证）',
	`certificateNo` varchar(255) DEFAULT NULL COMMENT '证件号码',
	`certificateDate` varchar(50) DEFAULT NULL COMMENT '其他证件有效期',
	`certificateUrl` varchar(255) DEFAULT NULL COMMENT '证件图片',
	`secondbirthday` varchar(50) DEFAULT NULL COMMENT '第二生日',
	`nation` tinyint(4) DEFAULT NULL COMMENT '国籍(1,境内；2，境外)',
	`endorsementType` tinyint(4) DEFAULT NULL COMMENT '签注类别',
	`endorsementOrgCode` varchar(255) DEFAULT NULL COMMENT '所持证件发证机关代码',
	`endorsementValidtime` varchar(50) DEFAULT NULL COMMENT '签证签注有效期',
	`endorsementStay` tinyint(4) DEFAULT NULL COMMENT '停留期（月）',
	`gotoCountry` varchar(50) DEFAULT NULL COMMENT '去往国',
	`comefromCountry` varchar(50) DEFAULT NULL COMMENT '来自国',
	`nationCode` varchar(255) DEFAULT NULL COMMENT '民族代码',
	`endorsementCode` varchar(255) DEFAULT NULL COMMENT '签证号',
	`healthCard` varchar(255) DEFAULT NULL COMMENT '健康证号码',
	`healthCardImg` varchar(255) DEFAULT NULL COMMENT '健康证明',
	`driverworkplace` varchar(255) DEFAULT NULL COMMENT '工作单位',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='驾驶员-备份表';
