DROP TABLE IF EXISTS `metadata_vehicle`;
CREATE TABLE `metadata_vehicle` (
	`id` bigint(11) DEFAULT NULL COMMENT 'id',
	`masterId` bigint(11) DEFAULT NULL COMMENT 'masterId',
	`plateNumber` varchar(100) DEFAULT NULL COMMENT '车牌号',
	`licenseNumber` varchar(100) DEFAULT NULL COMMENT '行驶证号码',
	`models` varchar(100) DEFAULT NULL COMMENT '车辆类型',
	`brand` varchar(100) DEFAULT NULL COMMENT '车辆品牌',
	`specification` varchar(100) DEFAULT NULL COMMENT '规格型号',
	`authority` varchar(255) DEFAULT NULL COMMENT '发证机关',
	`buyTime` varchar(255) DEFAULT NULL COMMENT '购买时间',
	`color` varchar(100) DEFAULT NULL COMMENT '车身颜色',
	`ownerName` varchar(100) DEFAULT NULL COMMENT '车主姓名',
	`ownerPhone` varchar(100) DEFAULT NULL COMMENT '车主电话',
	`ownerAddress` varchar(255) DEFAULT NULL COMMENT '车主地址',
	`engineNumber` varchar(100) DEFAULT NULL COMMENT '发动机号',
	`frameNumber` varchar(100) DEFAULT NULL COMMENT '车架号',
	`steeringWheel` varchar(100) DEFAULT NULL COMMENT '方向盘',
	`startTime` varchar(255) DEFAULT NULL COMMENT '启用年份',
	`weight` double(8,2) DEFAULT NULL COMMENT '车重',
	`length` double(8,2) DEFAULT NULL COMMENT '车长',
	`height` double(8,2) DEFAULT NULL COMMENT '车高',
	`width` double(8,2) DEFAULT NULL COMMENT '车宽',
	`type` varchar(255) DEFAULT NULL COMMENT '燃油种类',
	`capacity` double(8,2) DEFAULT NULL COMMENT '容量',
	`seat` int(11) DEFAULT NULL COMMENT '吨位',
	`backupWheel` int(11) DEFAULT NULL COMMENT '备用轮胎',
	`registTime` varchar(255) DEFAULT NULL COMMENT '注册时间',
	`licenseImage` varchar(255) DEFAULT NULL COMMENT '行驶证拍照',
	`faceImage` varchar(255) DEFAULT NULL COMMENT '车辆正面',
	`leftfaceImage` varchar(255) DEFAULT NULL COMMENT '车辆左侧45度（前）',
	`rightfaceImage` varchar(255) DEFAULT NULL COMMENT '车辆右侧45度（前）',
	`leftbackImage` varchar(255) DEFAULT NULL COMMENT '车辆左侧45度（后）',
	`rightbackImage` varchar(255) DEFAULT NULL COMMENT '车辆右侧45度（后）',
	`faceWheel` int(11) DEFAULT NULL COMMENT '前轮胎个数',
	`backWheel` int(11) DEFAULT NULL COMMENT '后轮胎个数',
	`fplateNumber` varchar(200) DEFAULT NULL COMMENT '境外車牌號碼',
	`area` varchar(50) DEFAULT NULL COMMENT '所属国籍',
	`engineNo` varchar(200) DEFAULT NULL COMMENT '发动机号',
	`permittedWeight` varchar(50) DEFAULT NULL COMMENT '核定载质量',
	`passengers` varchar(50) DEFAULT NULL COMMENT '核定载客',
	`effectiveDates` varchar(50) DEFAULT NULL COMMENT '保险生效日期',
	`endDates` varchar(50) DEFAULT NULL COMMENT '保险终止日期',
	`vehicleType` varchar(50) DEFAULT NULL COMMENT '七座以下客車',
	`insuranceUrl` varchar(200) DEFAULT NULL COMMENT '保险单图片',
	`vehicleId` bigint(11) DEFAULT NULL COMMENT 'vehicleId',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='车辆';
